# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NMF <- function(X, k, F_init, G_init, error, iter) {
    .Call(`_MatrixFact_NMF`, X, k, F_init, G_init, error, iter)
}

ONMF <- function(X, k, F_init, G_init, error, iter) {
    .Call(`_MatrixFact_ONMF`, X, k, F_init, G_init, error, iter)
}

SO_BIN3 <- function(X, k, F_init, G_init, error, iter, tau, factor, step) {
    .Call(`_MatrixFact_SO_BIN3`, X, k, F_init, G_init, error, iter, tau, factor, step)
}

SO_NMF <- function(X, k, F_init, G_init, error, iter, tau, factor) {
    .Call(`_MatrixFact_SO_NMF`, X, k, F_init, G_init, error, iter, tau, factor)
}

SemiNMF <- function(X, k, F_init, G_init, error, iter) {
    .Call(`_MatrixFact_SemiNMF`, X, k, F_init, G_init, error, iter)
}

lognmf <- function(X, k, F_init, G_init, error, iter, tau, step) {
    .Call(`_MatrixFact_lognmf`, X, k, F_init, G_init, error, iter, tau, step)
}

log_test <- function(X, k, F_init, G_init, prob_t, error, iter, step) {
    .Call(`_MatrixFact_log_test`, X, k, F_init, G_init, prob_t, error, iter, step)
}

NMF_LOG <- function(X, k, F_init, G_init, error, iter, step) {
    .Call(`_MatrixFact_NMF_LOG`, X, k, F_init, G_init, error, iter, step)
}

sobin_test <- function(X, k, F_init, G_init, prob_t, error, iter, tau, factor, step) {
    .Call(`_MatrixFact_sobin_test`, X, k, F_init, G_init, prob_t, error, iter, tau, factor, step)
}

